services:
  saps-common-build:
    build:
      args: {}
      context: .
      dockerfile: docker/Dockerfile
    command: sleep 6000000
    image: ufcgsaps/saps-common:sqaaas
    #image: eoscsynergyapps/saps-common-sqaaas
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build

  saps-common-docs:
    command: sleep 6000000
    image: sphinxdoc/sphinx
    volumes:
    - source: ./saps-common
      target: /saps-common-repo
      type: bind
    working_dir: /saps-common-repo

  saps-common-testing:
    command: sleep 6000000
    image: maven:3-alpine
    volumes:
    - source: ./saps-common
      target: /saps-common-repo
      type: bind
    working_dir: /saps-common-repo

version: '3.7'

