version: "3.6"

services:
  common-build:
    build:
      args: {}
      context: .
      dockerfile: './saps-common/docker/Dockerfile '
    command: sleep 6000000
    image: eoscsynergyapps/saps-common
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build

  common-testing:
    image: "maven:3-alpine"
    container_name: common-testing
    hostname: common-testing
    volumes:
     - type: bind
       source: ./saps-common
       target: /saps-common-repo
    command: sleep 3600
    
  common-docs:
    image: "sphinxdoc/sphinx"
    container_name: common-docs
    hostname: common-docs
    volumes:
     - type: bind
       source: ./saps-common
       target: /saps-common-repo
    command: sleep 3600
