version: "3.6"

services:
  common-testing:
    image: "maven:3-alpine"
    container_name: common-testing
    hostname: common-testing
    volumes:
     - type: bind
       source: ./saps-common
       target: /saps-common-repo
    command: sleep 3600
